### ISSUE TITLE
Touchscreen gets disabled on Yoga 2 Pro

### ISSUE THREAD

**Issue by vladimiroltean** [mkopta/toggle-touchpad#1]
Hi,
Instead of controlling the touchpad, the script gets tricked into thinking that my ELAN touchscreen is actually a touchpad.
Here is the output of "xinput list":
> ⎡ Virtual core pointer                          id=2    [master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
> ⎜   ↳ SynPS/2 Synaptics TouchPad                id=13   [slave  pointer  (2)]
> ⎜   ↳ ELAN Touchscreen                          id=9    [slave  pointer  (2)]
> ⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
>     ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
>     ↳ Power Button                              id=6    [slave  keyboard (3)]
>     ↳ Video Bus                                 id=7    [slave  keyboard (3)]
>     ↳ Power Button                              id=8    [slave  keyboard (3)]
>     ↳ Lenovo EasyCamera                         id=10   [slave  keyboard (3)]
>     ↳ Ideapad extra buttons                     id=11   [slave  keyboard (3)]
>     ↳ AT Translated Set 2 keyboard              id=12   [slave  keyboard (3)]

By the way, it would be really nice if you added support for touchscreens as well :)

**Comment by mkopta** [comment]
Hi!

First, thank you very much for your feedback and your xinput list.

It got me thinking on how to solve this properly and I came up with this
sollution: toggle-touchpad will completely ignore everything that includes
/touchscreen/i. So I have released v1.3 with that. You can upgrade via gnome
shell extensions website (but frankly, I have no idea how and wasn't able to
update an extension there), or you can update by following instructions "How to
install manualy" (also applies to updating) on toggle-touchpad github page:

  https://github.com/mkopta/toggle-touchpad

Hope that fixes the issue for you. Please let me know.

Regarding the touchscreen support - I was thinking about extending the
toggle-touchpad so it could include this functionality, but it turned out to be
so much more complicated that it had to be, so I went another route and create
new project (basically fork), called toggle-touchscreen. Version 1.0 is
available on gnome extensions webpage already, but I have just (now) released
1.1, which makes the tray icon a bit more pleasant to the eyes. Not sure how
long will the process on approving the 1.1 will take so again, I will
recomend you to follow manual install instructions from the toggle-touchscreen
github homepage (don't be fooled by the screenshot, still haven't got to make
one):

  https://github.com/mkopta/toggle-touchscreen

Again, please let me know whether that works for you. I have no touchscreens
available to me for testing so, frankly, I have no idea whether this actually
works or not.

Hopefuly this combo of extensions will do what you wanted.

Best regards,
  Martin

**Comment by vladimiroltean** [comment]
Sorry to disappoint you, but here is the output of "xinput list" when run on a Lenovo Yoga 3 Pro, this time:
> ⎡ Virtual core pointer                          id=2    [master pointer  (3)]
> ⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
> ⎜   ↳ SYNA2B22:00 06CB:2714                     id=12   [slave  pointer  (2)]
> ⎜   ↳ ATML1000:00 03EB:8A0F                     id=13   [slave  pointer  (2)]
> ⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
>     ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
>     ↳ Power Button                              id=6    [slave  keyboard (3)]
>     ↳ Video Bus                                 id=7    [slave  keyboard (3)]
>     ↳ Power Button                              id=8    [slave  keyboard (3)]
>     ↳ Sleep Button                              id=9    [slave  keyboard (3)]
>     ↳ Lenovo EasyCamera                         id=10   [slave  keyboard (3)]
>     ↳ Ideapad extra buttons                     id=11   [slave  keyboard (3)]
>     ↳ AT Translated Set 2 keyboard              id=14   [slave  keyboard (3)]

The Synaptics touchpad is the one with id 12, but still isn't caught by your pattern matching algorithm.
I think the easiest solution that would universally work is to create a drop-down list of devices from which the user can select.

**Comment by mkopta** [comment]
Sorry to hear that. Unfortunately, I have no easy way to resolve this in general. However, you can easily edit the installed extension so it would match your device exactly. So I would suggest you to follow installation steps for `toggle-touchscreen` and then just edit the `extension.js` file and change the `_get_touchpad_id()` function. In case you need help, I can do it for you, but I guess you can manage to replace the simple regex with whatever you have (the "ATML1000:00" I suppose).

Sure, the generic dropdown menu to toggle devices would solve that too, but for various reasons I am not going to do that. Sorry.
